export const MENU = [
  {
    id: 'paneer',
    name: 'Paneer Butter Masala',
    blurb: 'Slow-simmered tomato gravy, fenugreek, fresh cream. Served with butter naan.',
    price: 'You let me draw whiskers on you again',
    priceShort: 'whiskers, again',
    tags: ['comfort', 'spicy'],
    minutes: 28,
    swatchA: '#c44a2c',
    swatchB: '#e67a4d',
  },
  {
    id: 'risotto',
    name: 'Mushroom & Spinach Risotto',
    blurb: 'Carnaroli rice, cremini, wilted spinach, parmesan, finished with butter.',
    price: 'You need to dance on Baby Doll (for real this time)',
    priceShort: 'Baby Doll, for real',
    tags: ['creamy', 'comfort'],
    minutes: 32,
    swatchA: '#5e6b3e',
    swatchB: '#a3a872',
  },
  {
    id: 'cacio',
    name: 'Cacio e Pepe',
    blurb: 'Tonnarelli, pecorino, cracked black pepper. Three ingredients, much suffering. (Experimental.)',
    price: 'You have to prank call one of the members of soho sobo gang in front of me',
    priceShort: 'soho sobo prank call',
    tags: ['pasta', 'experimental'],
    minutes: 18,
    swatchA: '#e8d9a8',
    swatchB: '#b89762',
  },
  {
    id: 'alfredo',
    name: 'Tortelloni Alfredo',
    blurb: 'Cheese tortelloni in a butter-parmesan emulsion. No cream, no shortcuts.',
    price: 'You let me bicep curl you x4',
    priceShort: 'bicep curl × 4',
    tags: ['pasta', 'creamy'],
    minutes: 22,
    swatchA: '#f0e3c4',
    swatchB: '#d4b370',
  },
  {
    id: 'thai',
    name: 'Thai Green Curry',
    blurb: 'Homemade green curry paste, coconut milk, basil. Jasmine rice on the side.',
    price: 'You let me bicep curl you x2',
    priceShort: 'bicep curl × 2',
    tags: ['spicy', 'comfort'],
    minutes: 26,
    swatchA: '#3d6b4a',
    swatchB: '#7fa37a',
  },
  {
    id: 'me',
    name: 'You Just Want To See Me',
    blurb: 'No food. Just the chef, on your doorstep, holding nothing but eye contact.',
    price: 'Free (only for now)',
    priceShort: 'free for now',
    tags: ['off-menu'],
    minutes: 12,
    swatchA: '#2a2723',
    swatchB: '#5c544a',
  },
  {
    id: 'custom',
    name: 'Custom Request',
    blurb: "Off-menu. Tell me what you're craving — leave the details in the note to chef.",
    price: 'Chef Harsh will decide',
    priceShort: "chef's call",
    tags: ['off-menu', 'surprise'],
    minutes: 30,
    swatchA: '#7a5c3a',
    swatchB: '#c9a05e',
  },
];

export const PALETTE = {
  bg: '#f4f0e8',
  surface: '#faf7f0',
  ink: '#1c1a16',
  muted: '#6b665c',
  accent: '#c0392b',
  line: '#1c1a1622',
};
